import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Providers from '../redux/Provider';
import store from '../redux/store';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <Providers>   
          <div className="wrapper">
            <Navbar />
              <main>{children}</main>
            <Footer />
          </div>
            </Providers>
      </body>
    </html>
  )
}
